create database PMGSY;
use PMGSY;
select * from pmgsy_scheme;

-- List unique states
SELECT DISTINCT STATE_NAME FROM pmgsy_scheme;

-- Show year range
SELECT MIN(YEAR_RANGE) AS start_year, MAX(YEAR_RANGE) AS end_year FROM pmgsy_scheme;

-- ROAD COMPLETION %
select
STATE_NAME ,
DISTRICT_NAME,
PMGSY_SCHEME,  
(NO_OF_ROAD_WORKS_COMPLETED/NO_OF_ROAD_WORK_SANCTIONED) * 100 AS ROAD_COMPLETION_PERCENTAGE
from pmgsy_scheme;

-- BRIDGE COMPLETION %
select
STATE_NAME ,
DISTRICT_NAME,
PMGSY_SCHEME,  
(NO_OF_BRIDGES_COMPLETED/NO_OF_BRIDGES_SANCTIONED) * 100 AS BRIDGE_COMPLETION_PERCENTAGE
from pmgsy_scheme;

-- ROADS BALANCE
select
STATE_NAME ,
DISTRICT_NAME,
PMGSY_SCHEME,  
(NO_OF_ROAD_WORK_SANCTIONED-NO_OF_ROAD_WORKS_COMPLETED) AS ROAD_BALANCE
from pmgsy_scheme;

-- BRIDGE BALANCE
select
STATE_NAME ,
DISTRICT_NAME,
PMGSY_SCHEME,  
(NO_OF_BRIDGES_SANCTIONED/NO_OF_BRIDGES_COMPLETED) * 100 AS BRIDGE_BALANCE
from pmgsy_scheme;

-- LENGTH BALANCE(5km)
select 
STATE_NAME ,
DISTRICT_NAME,
PMGSY_SCHEME,
(LENGTH_OF_ROAD_WORK_SANCTIONED_KM - LENGTH_OF_ROAD_WORK_COMPLETED_KM) AS LENGTH_BALANCED
from pmgsy_scheme;

-- FUND UTILIZATION %
select
STATE_NAME ,
DISTRICT_NAME,
PMGSY_SCHEME,
(EXPENDITURE_OCCURED_LAKHS / COST_OF_WORKS_SANCTIONED_LAKHS) * 100 AS UTILIZATION_PERCENTAGE
from pmgsy_scheme;

-- Top Performing States by Road Completion %
SELECT 
    STATE_NAME,
    (SUM(NO_OF_ROAD_WORKS_COMPLETED) / SUM(NO_OF_ROAD_WORK_SANCTIONED)) * 100 AS ROAD_COMPLETION_PERCENTAGE
FROM PMGSY_SCHEME
GROUP BY STATE_NAME
ORDER BY ROAD_COMPLETION_PERCENTAGE DESC
LIMIT 5;

 -- Lowest Performing States by Road Completion %
 SELECT 
    STATE_NAME,
    (SUM(NO_OF_ROAD_WORKS_COMPLETED) / SUM(NO_OF_ROAD_WORK_SANCTIONED)) * 100 AS ROAD_COMPLETION_PERCENTAGE
FROM PMGSY_SCHEME
GROUP BY STATE_NAME
ORDER BY ROAD_COMPLETION_PERCENTAGE 
LIMIT 5;

-- States with Highest Pending Work
SELECT 
    STATE_NAME,
    SUM((NO_OF_ROAD_WORK_SANCTIONED) - (NO_OF_ROAD_WORKS_COMPLETED)) AS PENDING_WORKS
FROM pmgsy_scheme
GROUP BY STATE_NAME
ORDER BY PENDING_WORKS DESC
LIMIT 5;

-- States with Highest Utilization %
select
STATE_NAME ,
(SUM(EXPENDITURE_OCCURED_LAKHS )/ SUM(COST_OF_WORKS_SANCTIONED_LAKHS)) * 100 AS UTILIZATION_PERCENTAGE
from pmgsy_scheme
GROUP BY STATE_NAME
ORDER BY UTILIZATION_PERCENTAGE DESC
LIMIT 5;

-- USING WHERE CLAUSE

SELECT 
    STATE_NAME,
    PMGSY_SCHEME,
    NO_OF_ROAD_WORK_SANCTIONED,
    NO_OF_ROAD_WORKS_COMPLETED,
    LENGTH_OF_ROAD_WORK_SANCTIONED_KM,
    LENGTH_OF_ROAD_WORK_COMPLETED_KM,
    COST_OF_WORKS_SANCTIONED_LAKHS,
    EXPENDITURE_OCCURED_LAKHS,

    -- 1. Road Completion Percentage
    ROUND((NO_OF_ROAD_WORKS_COMPLETED / NO_OF_ROAD_WORK_SANCTIONED) * 100, 2) AS ROAD_COMPLETION_PERCENTAGE,

    -- 2. Average Road Length per Work
    ROUND((LENGTH_OF_ROAD_WORK_SANCTIONED_KM / NO_OF_ROAD_WORK_SANCTIONED), 2) AS AVG_LENGTH_PER_ROAD_KM,

    -- 3. Financial Efficiency (Cost per KM Completed)
    ROUND((EXPENDITURE_OCCURED_LAKHS / LENGTH_OF_ROAD_WORK_COMPLETED_KM), 2) AS COST_PER_KM,

    -- 4. Physical vs Financial Progress Gap
    ROUND(
        ((NO_OF_ROAD_WORKS_COMPLETED / NO_OF_ROAD_WORK_SANCTIONED) * 100) 
        - ((EXPENDITURE_OCCURED_LAKHS / COST_OF_WORKS_SANCTIONED_LAKHS) * 100),
        2
    ) AS PROGRESS_GAP_PERCENT,

    -- 5. Target Achievement Status
    CASE 
        WHEN (NO_OF_ROAD_WORKS_COMPLETED / NO_OF_ROAD_WORK_SANCTIONED) * 100 >= 90 THEN 'Achieved'
        ELSE 'Pending'
    END AS TARGET_STATUS,

    -- 6. Share of National Works
    ROUND(
        (NO_OF_ROAD_WORK_SANCTIONED / (SELECT SUM(NO_OF_ROAD_WORK_SANCTIONED) FROM pmgsy_scheme) * 100),
        2
    ) AS SHARE_OF_NATIONAL_WORKS_PERCENT

FROM pmgsy_scheme
WHERE STATE_NAME = 'Gujarat';

-- Filtering by Scheme
SELECT STATE_NAME, DISTRICT_NAME, PMGSY_SCHEME, 
       ROUND((NO_OF_ROAD_WORKS_COMPLETED / NO_OF_ROAD_WORK_SANCTIONED) * 100, 2) AS ROAD_COMPLETION_PERCENTAGE
FROM pmgsy_scheme
WHERE PMGSY_SCHEME = 'PMGSY-II';

